
DROP TABLE IF EXISTS DEPARTMENT;
CREATE TABLE DEPARTMENT (
  departmentId INT NOT NULL AUTO_INCREMENT,
  departmentName VARCHAR(255) NOT NULL,
  description VARCHAR(255) NULL,
  PRIMARY KEY (departmentId)
)